# Generated by Django 5.0.7 on 2024-09-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
