# Generated by Django 5.0.7 on 2024-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_addcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advanced Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('LAA', 'Linux Administration and Automation')], max_length=50),
        ),
    ]
